#!/bin/bash -e
#U
#U NAME
#U    20-enable-ssh - image enable ssh by default
#U
#U SYNOPSIS
#U    20-enable-ssh <pi_distro_file>
#U
#U DESCRIPTION
#U    Inject raspbian ssh file into image
#U
#U OPTIONS
#U    
#U    pi_distro_mount_dir|[DEFAULT_PI_DISTRO_MOUNT_DIR] - image mount point directory
#U
#
function usage() {
# usage - Any comment in script starting with '#U' will show up in "usage"
  egrep "^#U" $0 | sed -e 's/^#U //g' -e 's/^#U//g'
  exit 1
}

pi_distro_mount_dir=${1:-${DEFAULT_PI_DISTRO_MOUNT_DIR?"$(usage)"}}

touch ${pi_distro_mount_dir}/ssh

