#!/bin/bash -e
#U
#U NAME
#U    25-set-hostname - image set hostname
#U
#U SYNOPSIS
#U    25-set-hostname <pi_distro_file> <pi_hostname>
#U
#U DESCRIPTION
#U    Inject raspbian wifi into wpa_supplicant.conf into image
#U
#U OPTIONS
#U    
#U    pi_distro_mount_dir|[DEFAULT_PI_DISTRO_MOUNT_DIR] - image mount point directory
#U    pi_hostname|[DEFAULT_PI_HOSTNAME]                 - hostname
#U
#
function usage() {
# usage - Any comment in script starting with '#U' will show up in "usage"
  egrep "^#U" $0 | sed -e 's/^#U //g' -e 's/^#U//g'
  exit 1
}

pi_distro_mount_dir=${1:-${DEFAULT_PI_DISTRO_MOUNT_DIR?"$(usage)"}}
pi_hostname=${2:-${DEFAULT_PI_HOSTNAME?"$(usage)"}}

echo "${pi_hostname}" > ${pi_distro_mount_dir}/etc/hostname

